tools/generators/ethereum/contract_parsing.go

go-ethereum ABI generator [drops underscores](https://github.com/ethereum/go-ethereum/blob/v1.9.12/accounts/abi/argument.go#L371) and transforms function name to camel case. Instead of `__beaconCallback`, we get `beaconCallback`. Instead of `open_keep`, we get `openKeep`. Here we introduce the same behaviour to our contract code generators.

Normalize function name to eliminate underscores

---

pkg/persistence/disk_persistence.go
pkg/persistence/disk_persistence_test.go

Refs https://github.com/keep-network/keep-ecdsa/issues/336
In this PR we need to check if the storage dir specified in the config .toml file under `[Storage]:DataDir` has the right read&write permission.

Checking if a storage dir is readable and writable

---

pkg/chain/ethereum/ethutil/ethutil.go
tools/generators/ethereum/contract.go.tmpl
tools/generators/ethereum/contract_non_const_methods.go.tmpl
tools/generators/ethereum/contract_non_const_methods_template_content.go
tools/generators/ethereum/contract_template_content.go

Refs https://github.com/keep-network/keep-core/issues/1479
In this PR we add the gas estimation functionality. This will be used by Keep applications to retrieve the estimation for a specific transaction.

Adding gas estimate function

---

tools/generators/ethereum/contract_parsing.go
tools/generators/ethereum/contract_parsing_test.go

Closes https://github.com/keep-network/keep-core/issues/1579
- In https://github.com/keep-network/keep-common/commit/8ca95ff9de561f251db07c48cdcdfb76da079670#diff-10b1a8d2fcd46a80a34cd1e5bdf789c7L198 we introduced `toCamelCase` which normalizes function names using the same strategy as go-ethereum. This was needed so that we can have `__beaconCallback` function in `BondedECDSAKeepFactory`.
- `toCamelCase` uppercases the first letter, no matter if the function name starts with `_` or not. For example, `getGroupMembers` becomes `GetGroupMembers`.
- In `buildMethodInfo` we create `dashedName`:
```
shortVarRegexp, err = regexp.Compile("([A-Z])[^A-Z]*")
// (...)
dashedName := strings.ToLower(string(shortVarRegexp.ReplaceAll(
[]byte(normalizedName),
[]byte("-$0"),
)))
```
Having the first …

Fix ethereum command function names

---

pkg/cache/cache.go
pkg/cache/cache_test.go

Time cache implementation safe for concurrent use without the need of additional locking and coordination. Extracted from `keep-ecdsa`, will be used there and for https://github.com/keep-network/keep-core/issues/1627.

Time cache

---

pkg/cache/cache.go
pkg/cache/cache_test.go

Previously, the cache was swept only on `Add` action which could be problematic because we may want to sweep the old entries earlier, especially for cases when `Add` is invoked rarely, like e.g. active keep check.

Allow to trigger cache sweep manually

---

tools/generators/ethereum/contract.go.tmpl
tools/generators/ethereum/contract_template_content.go

`from` address in call options for contract binding should be set to the address of the signer. `contractAddress` is supposed to be a destination of the call.

Fixed from address for contract call options

---

pkg/persistence/disk_persistence.go
pkg/persistence/disk_persistence_test.go

255 is a Unix length limit for most filesystems but some extensions like eCryptfs may impose lower limits. For eCryptfs it's 143 characters. We shouldn't be using file names longer than 128 characters anywhere so it makes sense to validate this limit in the persistence layer as a final check.
I have also improved the error handling in `moveAll` function. We are now explicit that we `os.Rename` only if the target directory does not exist (`os.IsNotExist(err)`) and we don't do that if it's any other type of an error. In such a case, we return from the function doing nothing.
We also no longer ignore errors from `ioutil.ReadDir`. If the error happens, we return from the function doing nothing.

Max file length of 128 characters, moveAll error handling improvements

---

pkg/chain/ethereum/ethutil/nonce.go
pkg/chain/ethereum/ethutil/nonce_test.go
tools/generators/ethereum/command.go.tmpl
tools/generators/ethereum/command_template_content.go
tools/generators/ethereum/contract.go.tmpl
tools/generators/ethereum/contract_non_const_methods.go.tmpl
tools/generators/ethereum/contract_non_const_methods_template_content.go
tools/generators/ethereum/contract_template_content.go

The nonce manager is used by the generated contracts to track the current nonce and update it after each successfully submitted transaction. Tracking the nonce locally is required when transactions are submitted from multiple goroutines or when Ethereum clients are deployed behind a load balancer and their mempools are not always in sync.
One important aspect that might not be clear at first is that we need to call `IncrementNonce()` only when the transaction has been successfully submitted to the mempool. Also, the nonce manager has to be a single instance stored between all contracts.
`NonceManager` itself does not provide any synchronization. All generated contracts use the transaction lock provided by the chain and that transaction lock makes nonces manipulation safe.
`NonceManager` …

Local nonce manager

---

pkg/chain/ethereum/config.go
pkg/chain/ethereum/ethutil/mine_waiter.go
pkg/chain/ethereum/ethutil/mine_waiter_test.go
pkg/cmd/cmd.go
tools/generators/ethereum/command.go.tmpl
tools/generators/ethereum/command_template_content.go
tools/generators/ethereum/contract.go.tmpl
tools/generators/ethereum/contract_non_const_methods.go.tmpl
tools/generators/ethereum/contract_non_const_methods_template_content.go
tools/generators/ethereum/contract_template_content.go

See https://github.com/keep-network/keep-core/pull/1803
For every submitted transaction, we check in the predefined intervals if the transaction has been mined already and if not, we increase the gas price by 20% and try to submit again.
The interval at which we check for transaction status, as well as the maximum gas price, can be configured.

TX gas price bids

---

pkg/chain/ethereum/blockcounter/blockcounter.go

In case block counter received a block with block number string that could not be parsed to an integer, we should log an error and skip the loop step (continue). Making any decisions based on the incorrect block number is not what we want to do.

Continue when block number could not be parsed

---

pkg/metrics/gauge.go
pkg/metrics/gauge_test.go
pkg/metrics/info.go
pkg/metrics/info_test.go
pkg/metrics/observer.go
pkg/metrics/observer_test.go
pkg/metrics/registry.go
pkg/metrics/registry_test.go

Added metrics package which provides tools useful for gathering and exposing system metrics for external monitoring tools.

Metrics package

---

pkg/metrics/observer.go

Added an immediate metric observation tick when observation process is triggered.

Immediate first metric observation tick

---

pkg/chain/ethereum/config.go

Defining ethereum account address in the config file is redundant as the value can be easily obtained from ethereum account read from the file defined in `KeyFile` property.
Refs: https://github.com/keep-network/keep-core/issues/1968

Removed ethereum account address from config

---

go.mod
go.sum
pkg/chain/ethereum/config.go
pkg/chain/ethereum/ethutil/rate_limiter.go
pkg/chain/ethereum/ethutil/rate_limiter_test.go

Refs: https://github.com/keep-network/keep-ecdsa/issues/524
Here we implement a rate-limiting wrapper for the Ethereum contract backend. Regarding the internals, it can limit the average number of requests per second using the token bucket algorithm and the request concurrency using a semaphore.

Implementation of the Ethereum rate limiter

---

pkg/diagnostics/diagnostics.go

Added diagnostics package which provides tools useful for registering diagnostics callbacks for a named sources and exposing diagnostics information as a JSON, where named sources are keys and callback results are values. Can be used for providing peers list to 3rdparty diagnostics tools (or potentially official dashboard application)

Diagnositcs package

---

.github/workflows/gosec.yml
pkg/chain/ethereum/ethutil/ethutil.go
pkg/generate/generate.go
pkg/persistence/disk_persistence.go
tools/generators/ethereum/contract.go
tools/generators/promise/promise.go
tools/generators/template/template.go

Refs: https://github.com/keep-network/keep-core/issues/2007
Here we introduce the [GoSec](https://github.com/securego/gosec) scan workflow to the Github Actions pipeline and deal with all discovered problems.
Summary of `#nosec` exceptions and their motivation:
1. https://github.com/keep-network/keep-common/blob/024f151c484a5c59a0667dd10907236303746450/pkg/chain/ethereum/ethutil/ethutil.go#L40
Rule G304: File path provided as taint input
Motivation: We use this line to read a local key file. There is no user input.
2. https://github.com/keep-network/keep-common/blob/024f151c484a5c59a0667dd10907236303746450/pkg/generate/generate.go#L47
Rule G104: Audit errors not checked
Rule G307: Deferring a method which returns an error
Motivation: This line is placed in the auxiliary generator code, …

Add GoSec workflow

---

pkg/persistence/disk_persistence.go
pkg/persistence/disk_persistence_test.go
pkg/persistence/encrypted_persistence.go
pkg/persistence/encrypted_persistence_test.go
pkg/persistence/persistence.go

Implemented a new `Snapshot` method in the disk persistence layer. It allows storing a unique timestamped snapshot
file of given data in a dedicated `snapshot` directory.

Add snapshot feature to the disk persistence layer

---

tools/generators/ethereum/contract_parsing.go

Refs: https://github.com/keep-network/keep-ecdsa/issues/574
Underscore prefixes should be trimmed while capitalizing and uncapitalizing the first letter of the event params. This change
is required because `abigen` does the same while generating the underlying contract binding so names must be aligned to
avoid compilation errors.

Trim underscore prefix while generating event params

---

tools/generators/ethereum/contract.go

Refs: https://github.com/keep-network/keep-ecdsa/issues/574
Added the possibility to omit the command output file argument and make the generation of the command files optional.

Introduce optional command generation

---

pkg/chain/ethereum/blockcounter/blockcounter.go
pkg/chain/ethereum/ethutil/ethutil.go
pkg/chain/ethereum/ethutil/rate_limiter.go
pkg/chain/ethereum/ethutil/rate_limiter_test.go

Refs: https://github.com/keep-network/keep-ecdsa/issues/574
Introduced custom `EthereumClient` interface which wraps several `go-ethereum` interfaces and use it as backend in the client wrappers. The main motivation is to improve wrappers usability. For example, logging and rate-limiting clients can now be used by the block counter and mining waiter tools.

Introduce custom Ethereum client interface

---

pkg/chain/ethereum/ethutil/confirmations.go
pkg/chain/ethereum/ethutil/ethutil.go

Refs: https://github.com/keep-network/keep-ecdsa/issues/574
Added the `WaitForChainConfirmation` function which provides the ability to check the chain state once the chain reaches the given block height.

Add chain confirmation waiter

---

pkg/chain/chainutil/chainutil.go

`WaitForBlockConfirmations` works with any chain implementation so it should not be placed in `/pkg/chain/ethereum/ethutil` where Ethereum-specific utils live.
From now on, the code using this util that works with chain abstractions can import `pkg/chain/chainutil` instead of having to import Ethereum implementation utilities.
See https://github.com/keep-network/keep-ecdsa/pull/592#discussion_r522094746 for reference.

Introduced separate package for chain-generic functions

---

pkg/chain/ethereum/config.go

Refs: https://github.com/keep-network/keep-ecdsa/issues/551
Refs: https://github.com/keep-network/keep-core/issues/2163
Added a new property in the Ethereum config which allow defining a minimum value of the operator's account balance below which an alert will be triggered.

Add `BalanceAlertThreshold` property

---

pkg/chain/ethereum/ethutil/nonce.go

Refs https://github.com/keep-network/keep-ecdsa/issues/604
Increased the `localNonceTrustDuration` value from 5 to 30 seconds. This change should help avoid nonce duplications in case the mempool synchronization process between the load-balanced Ethereum nodes takes more time than 5 seconds.

Increase the local nonce trust duration

---

pkg/chain/ethereum/ethutil/ethutil.go
pkg/chain/ethereum/ethutil/rate_limiter.go
pkg/chain/ethereum/ethutil/rate_limiter_test.go

Here we expose the `BalanceAt` method in the `EthereumClient` interface and add it to the rate-limiting wrapper.

Expose `BalanceAt` method

---

pkg/chain/ethereum/ethutil/signer.go
pkg/chain/ethereum/ethutil/signer_test.go
pkg/chain/local/signer.go
pkg/chain/local/signer_test.go

EthereumSigner provides functions to sign a message and verify a
signature using Ethereum-specific signature format. It also provides
functions for the conversion of a public key to address.
The code has been extracted from `keep-core` with slight modifications
that will allow it to be imported from `keep-core` and `keep-ecdsa`.
The code is being extracted to allow us decouple ethereum-specific
implementation functions we use in generic code of `keep-ecdsa` client,
especially in `node.go`.
Also extracted `localSigning` from `keep-core` as a `local.Signer`.
Having `local` `Signer` implementation in `keep-common` will let us not
duplicate the code between local chain implementations in `keep-core`
and `keep-ecdsa`.

EthereumSigner and local Signer

---

pkg/chain/ethereum/ethutil/resubscribe.go
pkg/chain/ethereum/ethutil/resubscribe_test.go
tools/generators/ethereum/contract.go.tmpl
tools/generators/ethereum/contract_events.go.tmpl
tools/generators/ethereum/contract_events_template_content.go
tools/generators/ethereum/contract_template_content.go

Refs https://github.com/keep-network/keep-ecdsa/issues/680
This PR is the first one in the series of PRs refactoring Ethereum event subscriptions mechanism I plan to open in the next few days.
You can see it in action here: https://github.com/keep-network/keep-ecdsa/pull/663.
So far resubscription logging was implemented in contract binding templates. There were three problems with that mechanism:
1. No resubscribe backoff. Each failed subscription was retried 5 seconds after it failed. For many individual subscriptions ECDSA client is opening, a massive retry with no backoff could be interpreted as misbehavior by a third party Ethereum provider and further attempts could be completely blocked. Some operators experienced it with Alchemy.
2. All the logging was on the warning level. With …

Subscription dance: backoff, logging, and test coverage

---

pkg/chain/ethereum/ethutil/subscribe_opts.go
tools/generators/ethereum/command.go.tmpl
tools/generators/ethereum/command_template_content.go
tools/generators/ethereum/contract.go.tmpl
tools/generators/ethereum/contract_events.go.tmpl
tools/generators/ethereum/contract_events_template_content.go
tools/generators/ethereum/contract_parsing.go
tools/generators/ethereum/contract_template_content.go

Refs https://github.com/keep-network/keep-ecdsa/issues/680
Depends on keep-network/keep-common#62
See https://github.com/keep-network/keep-ecdsa/pull/671
There are two major changes to Ethereum subscription API proposed here:
- new subscription API with `OnEvent` and `Pipe` functions,
- background monitoring loop pulling past events from the chain.
The first change should allow implementing some handler logic easier and to avoid complex logic leading to bugs such as https://github.com/keep-network/keep-core/issues/1333 or https://github.com/keep-network/keep-core/issues/2052.
The second change should improve client responsiveness for operators running their nodes against Ethereum deployments that are not very reliable on the event delivery front.
This code has been integrated with ECDSA …

New Ethereum event subscription API, background event pull loop

---

tools/generators/ethereum/contract_parsing.go

Here we modify the contract generator in order to add contract prefix (short name) to events subscriptions names. This change should prevent compile errors caused by redeclared names when two contracts declare the same event name.

Add contract prefix to events subscriptions names

---

tools/generators/ethlike/contract_parsing.go
tools/generators/ethlike/contract_parsing_test.go

The Go contract generator had been using the parsed contract data to
generate method and event code in an order that is currently randomized
due to the use of maps. The contract parser now forcibly sorts the
method and event slices by name to ensure a stable order in the
generated code, and thus avoid diffs for committed code unless there are
contract or code generator changes.

Stabilizer Muscles: Force a stable order on method and event information

---

go.mod
go.sum
pkg/chain/celo/config.go
pkg/chain/celo/config_test.go
pkg/chain/ethereum/config.go
pkg/chain/ethereum/config_test.go

`ContractAddress` method in both Ethereum's and Celo's config structs should return a plain `common.Address` type instead of a pointer. This should eliminate the need for nil-checks in the client code.

Refactor `ContractAddress` method in config structs

---

tools/generators/ethereum/command.go.tmpl
tools/generators/ethereum/command_template_content.go
tools/generators/ethereum/contract.go.tmpl
tools/generators/ethereum/contract_template_content.go

go-ethereum 1.10.0 has switched to denying non-EIP155 signatures by default.
Although our code uses go-ethereum's own ABI binding generation, the version
currently in our dependencies never added support for EIP155 signers, and
instead always uses Homestead signers for the transactors it provides helpers
for.
In the short term, this commit manually creates the transactor options for the
account key, forcing an EIP155 signer when doing signing. When the go-ethereum
dependency gets bumped past 1.9.25, we will be able to move back to
`NewKeyedTransactorWithChainID`, which uses an EIP155 signer under the hood.

Adjust Ethereum contracts to use EIP155 signer

---

tools/generators/ethlike/command.go.tmpl
tools/generators/ethlike/command_template_content.go
tools/generators/ethlike/contract.go.tmpl
tools/generators/ethlike/contract_template_content.go

go-ethereum 1.10.0 has switched to denying non-EIP155 signatures by default.
Although our code uses go-ethereum's own ABI binding generation, the version
currently in our dependencies never added support for EIP155 signers, and
instead always uses Homestead signers for the transactors it provides helpers
for.
In the short term, this commit manually creates the transactor options for the
account key, forcing an EIP155 signer when doing signing. When the go-ethereum
dependency gets bumped past 1.9.25, we will be able to move back to
`NewKeyedTransactorWithChainID`, which uses an EIP155 signer under the hood.

Backport: Adjust Ethereum contracts to use EIP155 signer

---

.github/workflows/client.yml
pkg/chain/ethlike/block_counter.go
pkg/chain/ethlike/token.go
pkg/diagnostics/diagnostics.go
pkg/metrics/registry.go
pkg/rate/limiter.go

As part of work on RFC-18 a job linting the Go code has been added to
`client.yml` workflow. Action for linting of Go code has been also added
(as separate repository) as part of this work.
Running the worklow with linting revealed a number of issues found
by the linter ([see here](https://github.com/keep-network/keep-common/runs/2379469245?check_suite_focus=true)).
All of them are also fixed as part of this PR.
@nkuba, after merging this PR into master please configure the
`client-lint` job in GitHub's settings as required for PR merging.

Add Go linting to the client.yml workflow

---

tools/generators/ethlike/contract_non_const_methods.go.tmpl
tools/generators/ethlike/contract_non_const_methods_template_content.go

The logged message didn't contain a space between method name and params (resulted in e.g. `submitPublicKeyparams:`). 
In this PR we added a space.
Sample message that used to be logged:
```
2021-06-01T16:03:57.284+0200	DEBUG	keep-contract-BondedECDSAKeep	submitting transaction submitPublicKeyparams: [49 219 244 160 164 177 151 147 225 55 231 231 13 50 114 78 174 57 148 142 172 39 121 149 129 195 214 68 39 231 163 221 134 243 60 24 160 47 117 146 221 39 240 12 61 223 158 199 217 56 123 186 74 106 19 207 204 16 203 241 234 62 64 254]
```
The second commit we included in this PR is a simplification. As `Hash` type implements the` String()` function we can use `%s` in logger message format to log the value as hexadecimal string.

Added missing space in the transaction submission message

---

.github/workflows/client.yml

Use of the `master` and `slave` terms in the computer industry is
widespread, but has been recently discouraged, as it was brought to
attention that the terms may be considered offensive.
GitHub has already moved their default repositories from the `master`
to `main` in many places. We're planning to do the same for our
repositories, this however requires some changes in the code.
After the proposed changes get merged to the `master` branch, the
repository should be ready for the migration from `master` to `main`.
To migrate from `master` to `main`:
1. Do a local branch rename with `git branch -m master main`
2. Push the renamed branch `git push -u origin main`
3. In the Github repo settings, rename the default branch: Settings ->
Branches -> Default branch -> (pencil icon) -> (change …

Migrate from `master` to `main` branch

---

pkg/chain/celo/celoutil/balance_monitor.go
pkg/chain/ethereum/ethutil/balance_monitor.go
pkg/chain/ethlike/balance_monitor.go
pkg/chain/ethlike/balance_monitor_test.go
pkg/wrappers/wrappers.go
pkg/wrappers/wrappers_test.go

We want to use a retry mechanism for single executions of the balance check.
The retries will be performed during the period of `retryTimeout`, logging a warning on each error. When the timeout is hit an error will be logged and retries stopped. The next balance check will be triggered at the next tick.

Balance monitoring retries

---

.github/workflows/client.yml

The purpose of this PR is to set a cron job that would run tests and builds on a daily basis (at midnight) so the results can be displayed on Meercode dashboard.

Adding cron for daily tests and builds on Mercodee

---

pkg/chain/celo/celoutil/adapter.go
pkg/chain/celo/celoutil/adapter_test.go
pkg/chain/celo/celoutil/celoutil.go
pkg/chain/celo/celoutil/mining_waiter.go
pkg/chain/celo/celoutil/mining_waiter_test.go
pkg/chain/ethereum/config.go
pkg/chain/ethereum/ethutil/adapter.go
pkg/chain/ethereum/ethutil/adapter_test.go
pkg/chain/ethereum/ethutil/ethutil.go
pkg/chain/ethereum/ethutil/mining_waiter.go
pkg/chain/ethereum/ethutil/mining_waiter_test.go
pkg/chain/ethlike/chain.go
pkg/chain/ethlike/mining_waiter.go
pkg/chain/ethlike/mining_waiter_test.go
pkg/cmd/cmd.go
tools/generators/ethlike/command.go.tmpl
tools/generators/ethlike/command_template_content.go
tools/generators/ethlike/contract.go.tmpl
tools/generators/ethlike/contract_non_const_methods.go.tmpl
tools/generators/ethlike/contract_non_const_methods_template_content.go
tools/generators/ethlike/contract_template_content.go

This pull request adds support of EIP-1559 to the mining waiter. Specific changes include:
- Refactoring of the mining waiter structure and preserving current functionality for legacy Ethereum and Celo transactions
- Getting rid of the mining waiter from `ethlike` package. Now Ethereum and Celo have their own implementations and all differences lying in transaction internals are well encapsulated
- Update of contract bindings generator to capture changes in the mining waiter
- Unit tests and documentation
- Applying changes in client repositories

Support EIP-1559 in the mining waiter

---

pkg/chain/ethereum/config.go
pkg/chain/ethereum/config_test.go

We want to return a specific error when a contract address is not configured so the client can handle such scenario with an alternative path.

Return a specific error when contract address is not found

---

pkg/chain/ethereum/token.go
pkg/chain/ethereum/wei.go
pkg/chain/ethereum/wei_test.go

We want to print Wei value with units. For example, instead of printing `7654300000000000000` we want to read a string `7.6543 ether`.

Implement .String() for ethereum.Wei

---

pkg/rate/limiter.go

We were missing default values for the limiter that can be used by the
client.

Define defaults for the rate limiter

---

pkg/chain/ethereum/config.go

The function should be used to configure addresses in the
ContractAddresses mapping. We're storing the contracts at a specific key
(lowercased) and we want to be consistent about that in all getters and
setters.

Expose SetContractAddress function

---

pkg/chain/ethereum/config.go

The mapping could exist but the address could be an empty string. In
such scenario we should verify also `addressString == ""` and return an
ErrAddressNotConfigured error.

Check if contract address is empty string and return error

---

pkg/chain/ethereum/config.go
pkg/chain/ethereum/network.go
pkg/chain/ethereum/network_test.go

We add Network enumeration of supported Ethereum Networks like Mainnet
and Goerli. We include a property specifing the network in the
ethereum.Config struct.

Configure Ethereum network as enum in the etherem config

---

pkg/chain/ethereum/network.go

Each Ethereum network works with an associated Chain ID.
Here we expose a function that returns a chain id for the network.
The Chain ID will be used by the client for validation.
Depends on https://github.com/keep-network/keep-common/pull/99

Define Chain ID for Ethereum Network

---

README.adoc

We're adding a badge to the README file which shows the status of the workflow building and testing the Go code in the `keep-common` repository. The displayed status is based the status of the most recently executed `Go` workflow triggered by the push to `main`.
Refs:
https://github.com/threshold-network/token-dashboard/pull/296
https://github.com/keep-network/coverage-pools/pull/218
https://github.com/keep-network/keep-core/pull/3398
https://github.com/keep-network/sortition-pools/pull/194
https://github.com/keep-network/tbtc-v2/pull/420

Add the status badge to README

---

tools/generators/ethereum/command.go.tmpl
tools/generators/ethereum/command_template_content.go
tools/generators/ethereum/contract_parsing.go

A struct can be nested inside a slice. For such types, we need to add
`abi.` prefix similar to what we do for tuples.
Another change we added in this PR is some context message for transaction simulation to be clear that
the transaction was just simulated and it has to be rerun with
`--submit` flag if the user wants it to have an effect.

Handle abi prefix for structs nested in slices

---

README.adoc

The `shields.io` have changed the syntax of the endpoints generating status badges, resulting in showing false failure status when old syntax was used. Updating the READMEs to use the new syntax.
Read more: badges/shields#8671.
Refs:
https://github.com/keep-network/sortition-pools/pull/198
https://github.com/keep-network/keep-core/pull/3449
https://github.com/keep-network/tbtc-v2/pull/429
https://github.com/keep-network/coverage-pools/pull/221

Fix badges after change in shields.io syntax

---

pkg/chain/ethereum/balance_monitor.go
pkg/wrappers/wrappers.go
pkg/wrappers/wrappers_test.go

Instead of using `context.Background()` context in the wrappers we require a parent context to be passed so the retries and waits are correctly aborted when the parent context is done.

Require parent context in wrappers

---

tools/generators/ethereum/contract_events.go.tmpl
tools/generators/ethereum/contract_events_template_content.go

A client might experience some connectivity issues with Alchemy / Infura and will retry to reconnect. These attempts shouldn't be logged at the Error level as they don't require any actions from the operator.

Changing connectivity retry attempts from Error to Warn level

---

.github/workflows/client.yml

Node 12 has been out of support since April 2022, as a result GitHub has started the deprecation process of Node 12 for GitHub Actions. They plan to migrate all actions to run on Node16 by Summer 2023. Some of the GH Marketplace actions that we've been using in our workflows were running on `node12`, but have already published new versions running on `node16`. We're updating those actions to the latest versions.
Read more on
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Use actions running on `node16`

---

pkg/utils/decode/bytes.go
pkg/utils/decode/bytes_test.go
tools/generators/ethereum/contract_parsing.go

There are quite a few functions in our Solidity contracts that accept `bytes20` or `bytes32` as a parameter. One of many examples are [`requestHeartbeat(bytes20 walletPubKeyHash, bytes calldata message)`](https://github.com/keep-network/tbtc-v2/blob/eddb2b5f9468daf18f27c45c06b70ab05bda78ef/solidity/contracts/bridge/WalletCoordinator.sol#L352) from the `WalletCoordinator` contract and [`getWallet(bytes32 walletID)`](https://github.com/keep-network/keep-core/blob/6302a42470772762b63cf6f584878aa5d4d4d2d2/solidity/ecdsa/contracts/WalletRegistry.sol#L1054) from the `WalletRegistry` contract. Given there was no parsing function defined in our Ethereum contract parsing logic, all functions accepting `bytes32` and `bytes20` were skipped during the code generation:
```
WARNING: Unsupported param …
```

Support bytes20 and bytes32 in Ethereum contract bindings

---

pkg/chain/ethereum/network.go
pkg/chain/ethereum/network_test.go

The Görli testnet currently used by Threshold/Keep for development purposes is planned to become deprecated with the end of year 2023. The testnet that was created to replace it is called
[Holešky](https://github.com/eth-clients/holesky), however it will take some time until it gets integrated with by some of the projects we rely on. As a solution, we decided to switch first to another testnet that is currently live - Sepolia. This testnet's EOL is planned for 2026, which gives us plenty of time to move to Holešky before Sepolia gets deprecated. Until Görli is not dead we want to support both testnets.

Add Sepolia to the list of supported networks

---

pkg/chain/ethereum/network.go
pkg/chain/ethereum/network_test.go

As the Goerli testnet will become deprecated with end of year 2023 and we've already migrated to Sepolia testnet, we'll no longer need the Goerli-related code past that date.
Ref: https://github.com/threshold-network/solidity-contracts/issues/150

Remove support for Goerli testnet
